[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "functions"
  
[functions.analyze]
  timeout = 90

# Redirect all API routes to Netlify Functions
[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200

[[redirects]]
  from = "/api/providers"
  to = "/.netlify/functions/providers"
  status = 200

[[redirects]]
  from = "/api/test-segmentation"
  to = "/.netlify/functions/test-segmentation"
  status = 200

[[redirects]]
  from = "/api/segment-panels"
  to = "/.netlify/functions/segment-panels"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8893
  publish = ".next"
  functions = "functions"
  functionsTimeout = 90

  [context.dev.environment]
    OPENAI_FORMAT_API_URL = "https://ark.cn-beijing.volces.com/api/v3"
    OPENAI_FORMAT_API_KEY = "0b18782d-6378-444d-bbea-1ead747570f0"
    OPENAI_FORMAT_MODEL = "doubao-seed-1-6-lite-251015"